config/routes.rb
Rails.application.routes.draw do

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

root 'tasks#index' #root is welcome controller and index action


get 'items/new' 
get 'welcome/index'
get 'tasks/about'
get 'tasks/index'


resources :tasks;
resources :items;

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end
#The methods here are passed down to all children classses

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @title = "Gd Progress";
  end



  def new

    @title = "My new Items page";

  end

  def create 
    render plain:params[:item].inspect
  end
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all

    @search = Task.search(params[:q])
    @products = @search.result
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  def about
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:task_name, :detail, :tag)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_header.html.erb
 <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

 <div class="container-fluid">
    <%
=begin%>
 <a class="navbar-brand" href="../tasks/new">Navbar</a> 
<%
=end%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

      <%= link_to  "Home", tasks_index_path,class:"navbar-brand" %>

      <%= link_to  "About Me", tasks_about_path,class:"navbar-brand" %>
        <%
=begin%>
 <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li> 
<%
=end%>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-secondary" type="submit">Search</button>
      </form>
    </div>
  </div> 

</nav> 

app/views/items/index.html.erb
<h1><%= @title %></h1>
<p>Find me in app/views/items/index.html</p>

<%= text_field(:person, :name) %>

<%= form_for :item do |f| %>

<p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
</p>

<% end %>

app/views/items/new.html.erb
<%= javascript_pack_tag 'index' %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>Tasks</title>

        <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <%= render "items/header" %> 
  <body>
    
<!--renders the partial file for the nav bar on all pages -->
    <%= yield %>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
    
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<br/>
  <div class="field">
    <%
=begin%>
 <%= form.label :task_name,class:"h6" %> 
<%
=end%>
    <%= form.text_field :task_name,class:"form-control",id:"floatingInput", placeholder:"Task"%>
  </div>

  <div class="field">
    <%
=begin%>
 <%= form.label :detail,class:"h6"  %> 
<%
=end%>
    <%= form.text_field :detail,class:"form-control",placeholder:"Details"%>
  </div>

  <div class="field">
    <%= form.text_field :tag,class:"form-control",placeholder:"Tag"%>
  </div>
<br/>
  <div class="actions">
    <%= form.submit class:"btn" %>
  </div>

<% end %>

app/views/tasks/about.html.erb
<H1>Happy to have the opportunity to work on this assignment though I was not able to fully design
all the pages in time</H1>

 <%= javascript_pack_tag 'index' %> 

app/views/tasks/edit.html.erb
<br/>
<%= render 'form', task: @task %>
<br/>
<%= link_to 'Show', @task,class:"btn"  %> 
<%= link_to 'Back', tasks_path,class:"btn"  %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<%
=begin%>
 <%= search_form_for @search do |f| %>
  <div class="field">

    <%= f.label :task_name_cont,"DSFFSA"%>
    <%= f.search_field :task_name_cont %>

</div>

<%= f.submit "Search" %>

<%end%>

<%= search_form_for(@search, format: :pdf) do |f| %>
<%end%>

 <%= search_form_for(@search, format: :json) do |f| %> 
<%end%>

<br/> 
<%
=end%>

<h1>Tasks</h1>

<table class="table table-hover table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Detail</th>
      <th>Tag</th>  
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.task_name %></td> 
        <td><%= task.detail %></td>
        <td><%= task.tag %></td>
        <td><%= link_to 'Show', task ,class:"btn btn-light btn-sm"%></td>
        <td><%= link_to 'Delete', task, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-outline-danger btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path ,class:"btn"%>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path, class:"btn" %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Task name:</strong>
  <%= @task.task_name %>
</p>

<p>
  <strong>Detail:</strong>
  <%= @task.detail %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @task.tag %>
</p>

<%= link_to 'Edit', edit_task_path(@task), class:"btn" %> 
<%= link_to 'Back', tasks_path, class:"btn" %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>